export const SET_GAME_STARTED = 'SET_GAME_STARTED';

export const SET_ADVENTURE_LOG_DATA = 'SET_ADVENTURE_LOG_DATA';
export const SET_ADVENTURELOG_EXPANDED = 'SET_ADVENTURELOG_EXPANDED';

export const SET_CARD_EXPANDED = 'SET_CARD_EXPANDED';

export const SET_NOTEBOOK_DATA = 'SET_NOTEBOOK_DATA';
export const SET_NOTEBOOK_EXPANDED = 'SET_NOTEBOOK_EXPANDED';

export const SET_DRAWING_ENABLED = 'SET_DRAWING_ENABLED';

export const SET_SCARCITY_ABUNDANCE_EXPANDED = 'SET_SCARCITY_ABUNDANCE_EXPANDED';

export const CARD_DRAW = {
  FETCH_SUCCESS: 'CARD_DRAW_FETCH_SUCCESS',
  FETCH_ERROR: 'CARD_DRAW_FETCH_ERROR',
};

export const LOG = {
  FETCH_SUCCESS: 'LOG_FETCH_SUCCESS',
  FETCH_ERROR: 'LOG_FETCH_ERROR',
};

export const NOTE = {
  FETCH_SUCCESS: 'NOTE_FETCH_SUCCESS',
  FETCH_ERROR: 'NOTE_FETCH_ERROR',
};

export const SCARCITY_ABUNDANCE = {
  FETCH_SUCCESS: 'SCARCITY_ABUNDANCE_FETCH_SUCCESS',
  FETCH_ERROR: 'SCARCITY_ABUNDANCE_FETCH_ERROR',
};

export const OUT_OF_TURN_ACTION = {
  FETCH_SUCCESS: 'OUT_OF_TURN_ACTION_FETCH_SUCCESS',
  FETCH_ERROR: 'OUT_OF_TURN_ACTION_FETCH_ERROR',
};

// test code
export const SEND_WEBSOCKET_MESSAGE = 'SEND_WEBSOCKET_MESSAGE';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
