export const SET_GAME_STARTED = 'SET_GAME_STARTED';
export const SET_ADVENTURELOG_EXPANDED = 'SET_ADVENTURELOG_EXPANDED';
export const SET_NOTEBOOK_EXPANDED = 'SET_NOTEBOOK_EXPANDED';

export const DECK = {
  FETCH_SUCCESS: 'DECK_FETCH_SUCCESS',
  FETCH_ERROR: 'DECK_FETCH_ERROR'
}

export const DECK_DRAW = {
  FETCH_SUCCESS: 'DECK_DRAW_FETCH_SUCCESS',
  FETCH_ERROR: 'DECK_DRAW_FETCH_ERROR'
}