export const DATA = {
  SAVE_LOG: 'SAVE_LOG_DATA',
  SAVE_ACTION: 'SAVE_ACTION_DATA',
  DRAWN_CARD: 'DRAWN_CARD_DATA',
  MOUSE: 'MOUSE_DATA',
  NOTE: 'NOTE_DATA',
  SCARCITY: 'SCARCITY_DATA',
  ABUNDANCE: 'ABUNDANCE_DATA',
  NAME: 'NAME_DATA',
  GAMERTAG: 'GAMERTAG_DATA',
  DISCUSSION: 'DISCUSSION_DATA',
  DESCRIPTION: 'DESCRIPTION_DATA',
  INCOMPLETE_PROJECTS_LIST: 'INCOMPLETE_PROJECTS_LIST_DATA',
  GAME_STATE: 'GAME_STATE_DATA',
  SEASON: 'SEASON',
};

export const ACTIONS = {
  ADD_PLAYER: 'ADD_PLAYER',
  START_GAME: 'START_GAME',
  START_TURN: 'START_TURN',
  START_PROJECT: 'START_PROJECT',
  END_TURN: 'END_TURN',
  END_DRAWING: 'END_DRAWING',
  TRANSFER: 'TRANSFER',
  DISCUSS: 'DISCUSS',
  SELECTED_PROMPT: 'SELECTED_PROMPT',
  COMPLETE_PROJECT: 'COMPLETE_PROJECT',
  ADD_RESOURCES: 'ADD_RESOURCES',
  ADD_ABUN_SCARC: 'ADD_ABUN_SCARC',
  PREP_GAME: 'PREP_GAME',
  SELECT_INCOMPLETE_PROJECT: 'SELECT_INCOMPLETE_PROJECT',
  ADD_DESCRIPTION: 'ADD_DESCRIPTION',
};

export const UPDATE = {
  LOGS: 'UPDATE_LOGS',
  ACTION: 'UPDATE_ACTION',
  NOTEBOOK: 'UPDATE_NOTEBOOK',
  SCARCITY_ABUNDANCE: 'UPDATE_SCARCITY_ABUNDANCE',
  ENABLE_DRAWING: 'ENABLE_DRAWING',
  DISCUSSION: 'UPDATE_DISCUSSION',
  PROJECT: 'UPDATE_PROJECT',
  FIRST_PLAYER_GAME_PREP: 'FIRST_PLAYER_GAME_PREP',
  GAME_STARTED: 'GAME_STARTED',
  NO_ONGOING_PROJECTS: 'NO_ONGOING_PROJECTS',
};

export const SECOND_ACTION = {
  DISCOVERY: 'ACTION_DISCOVERY',
  PROJECT: 'ACTION_PROJECT',
  DISCUSSION: 'ACTION_DISCUSSION',
};

export const SECOND_TURN = {
  ACTION: 'SECOND_TURN_ACTION',
};
