export const SAVE_LOG_DATA = 'SAVE_LOG_DATA';
export const SAVE_ACTION_DATA = 'SAVE_ACTION_DATA';
export const DRAWN_CARD_DATA = 'DRAWN_CARD_DATA';
export const MOUSE_DATA = 'MOUSE_DATA';
export const NOTE_DATA = 'NOTE_DATA';
export const SCARCITY_DATA = 'SCARCITY_DATA';
export const ABUNDANCE_DATA = 'ABUNDANCE_DATA';
export const NAME_DATA = 'NAME_DATA';
export const GAMERTAG_DATA = 'GAMERTAG_DATA';
export const DISCUSSION_DATA = 'DISCUSSION_DATA';
export const DESCRIPTION_DATA = 'DESCRIPTION_DATA';

export const ADD_PLAYER = 'ADD_PLAYER';
export const START_GAME = 'START_GAME';
export const START_TURN = 'START_TURN';
export const START_PROJECT = 'START_PROJECT';
export const END_TURN = 'END_TURN';
export const END_DRAWING = 'END_DRAWING';
export const SUBMIT_ACTION = 'SUBMIT_ACTION';
export const TRANSFER = 'TRANSFER';
export const DISCUSS = 'DISCUSS';

export const SELECTED_PROMPT = 'SELECTED_PROMPT';

export const UPDATE_LOGS = 'UPDATE_LOGS';
export const UPDATE_ACTION = 'UPDATE_ACTION';
export const UPDATE_NOTEBOOK = 'UPDATE_NOTEBOOK';
export const UPDATE_SCARCITY_ABUNDANCE = 'UPDATE_SCARCITY_ABUNDANCE';
export const ENABLE_DRAWING = 'ENABLE_DRAWING';
export const UPDATE_DISCUSSION = 'UPDATE_DISCUSSION';
export const SECOND_ACTION_DISCOVERY = 'ACTION_DISCOVERY';
export const SECOND_ACTION_PROJECT = 'ACTION_PROJECT';
export const SECOND_ACTION_DISCUSSION = 'ACTION_DISCUSSION';
export const SECOND_TURN_ACTION = 'SECOND_TURN_ACTION';